{
    'name': '3PL Integration Core',
    'version': '15.0.1.0.0',
    'category': 'Inventory/Inventory',
    'summary': 'Forwarder-agnostic 3PL warehousing integration platform',
    'depends': ['mml_base', 'mail', 'stock', 'sale_management', 'purchase'],
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'external_dependencies': {'python': ['paramiko']},
    'data': [
        'security/ir.model.access.csv',
        'data/cron.xml',
        'views/connector_views.xml',
        'views/message_views.xml',
        'views/menu.xml',
    ],
    'author': 'MML',
    'license': 'OPL-1',
    'auto_install': False,
    'installable': True,
    'application': False,
}
