{
    'name': '3PL Integration \u2014 Mainfreight',
    'version': '15.0.2.0.0',
    'category': 'Inventory/Inventory',
    'summary': 'Mainfreight Warehousing 3PL integration',
    'author': 'MML',
    'license': 'OPL-1',
    'depends': ['stock_3pl_core'],
    'data': [
        'security/ir.model.access.csv',
        'views/connector_mf_views.xml',
        'views/picking_mf_views.xml',
        'views/warehouse_mf_views.xml',
        'views/pipeline_views.xml',
        'views/exception_views.xml',
        'views/discrepancy_views.xml',
        'views/kpi_dashboard_action.xml',
        'views/menu_mf.xml',
        'data/tracking_cron.xml',
        'data/inbound_cron.xml',
        'data/phase2_defaults.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'stock_3pl_mainfreight/static/src/js/mf_kpi_dashboard.js',
            'stock_3pl_mainfreight/static/src/xml/mf_kpi_dashboard.xml',
        ],
    },
    'controllers': ['controllers/webhook.py'],
    'demo': ['data/connector_mf_demo.xml'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
